### ISSUE TITLE
Where is ScaleBias layers?

### ISSUE THREAD

**Issue by ducha-aiki** [smichalowski/google_inception_v3_for_caffe#2]
Original BN paper uses Scale-bias y=kx+b after BatchNorm. Are you omitting them intentionally?

**Comment by smichalowski** [comment]
Ive followed MXNET implementation creating this caffe prototxt. Have you tried to train this network with scale filter ?

**Comment by ducha-aiki** [comment]
Not this, but other networks. 
MXNet like other frameworks, and unlike caffe has scale-bias (gamma) inside batchnorm layer. While caffe-maintainers decided to have separate scale-bias layer
https://github.com/BVLC/caffe/pull/3591 
https://github.com/BVLC/caffe/pull/3161 
https://github.com/BVLC/caffe/pull/3229

**Comment by smichalowski** [comment]
It seems you are right. Ill check your prototxt and merge your PR. Thank you :)

**Comment by ducha-aiki** [comment]
@smichalowski you are welcome :)
P.S. It could be that real performance difference will be really small.
